### ISSUE TITLE
Latest version has missing method exception

### ISSUE THREAD

**Issue by camer314** [Microsoft/BotBuilder-Location#108]
Since bot framework version  > 3.5.3 the control gets a missing method exception 

Method not found: 'Void Microsoft.Bot.Builder.Dialogs.PromptDialog.Confirm(Microsoft.Bot.Builder.Dialogs.IDialogContext, Microsoft.Bot.Builder.Dialogs.ResumeAfter`1<Boolean>, System.String, System.String, Int32, Microsoft.Bot.Builder.Dialogs.PromptStyle)

A comment on a previous issue mentioned for them it was resolved in 3.8 but for me the issue still exists.

The problem is the assembly still has a reference to 3.3 of BotBuilder.

**Comment by garypretty** [comment]
I am seeing the same issue

**Comment by ejadib** [comment]
Related to #107

**Comment by kgrashad** [comment]
Released https://www.nuget.org/packages/Microsoft.Bot.Builder.Location?NormalizedVersion=2.1.0
