### ISSUE TITLE
bot geo location

### ISSUE THREAD

**Issue by ne00346536** [Microsoft/BotBuilder-Location#110]
Hi,

I want to capture the bot geo location and then displaying the offers available at his presence. I have gone through bing location API but there we have to input the address data in query parameter as a rest service  then only it will return the lat and long values.

 1) I need to capture the lat and long values of bot(user) geo location
 2) Need to capture the postal code from bot geo location.

Can you please let me know how can I achieve the above mentioned two requirements.

Thanks.

**Comment by ne00346536** [comment]
Hi , Can anyone please provide details on this.

Thanks.

**Comment by rbrundritt** [comment]
This is not available in most bot platforms. Some do provide access to the users location but they need to set this up and explicitly share their location information. There are two possible options; ask the user for their location, which this API does, or possibly use the users IP address and do a reverse lookup which could give you the city they are in. However some platforms will likely give you the IP address of the server of the bot platform the request was passed through.
