### ISSUE TITLE
Method not found exception Bot with QnA maker

### ISSUE THREAD

**Issue by rohantare** [Microsoft/BotBuilder-Location#111]
Hello,

I am using Visual studio 2017 with Bot framework 3.8.1. Created simple QnA Maker dialog using with cognitive services 1.1.0.
QnA maker is working fine, I have tested it online. However when I test the bot which triggers QnA maker I get following  exception : 

Exception: Method not found: 'Void Microsoft.Bot.Builder.Dialogs.PromptOptions`1..ctor(System.String, System.String, System.String, System.Collections.Generic.IReadOnlyList`1<!0>, Int32, Microsoft.Bot.Builder.Dialogs.PromptStyler, System.Collections.Generic.IReadOnlyList`1<System.String>)'.",

This works well when I develop using Visual Studio 2015.

What could be the issue?

**Comment by ejadib** [comment]
This is the wrong repo, please refer to https://github.com/Microsoft/BotBuilder-CognitiveServices/issues/28

**Comment by rohantare** [comment]
Appologies. Shall I create a new issue there?

**Comment by rohantare** [comment]
I have update the issue there. Let's close this one!
