### ISSUE TITLE
Can't send location in Facebook Messenger web

### ISSUE THREAD

**Issue by cesarvarela** [microsoft/BotBuilder-Location#112]
Right now you can't send locations to a Facebook page when using Facebook web interface, I think the prompt should allow users to manually type an address like it does in other channels.

![image](https://user-images.githubusercontent.com/1172479/26961809-f5bd40a6-4cb7-11e7-9b40-18a92c431c8d.png)

![image](https://user-images.githubusercontent.com/1172479/26961814-fdc43692-4cb7-11e7-8798-b27d8b980dff.png)

**Comment by NiteLordz** [comment]
I just found this out.  I was expecting same functionality to be Send Location button or text input. This makes this a show stopper for me on the Facebook channel.

**Comment by q3blend** [comment]
We have a work item for this in our backlog.

**Comment by IoTGirl** [comment]
You can send a custom URL as documented here: https://docs.microsoft.com/en-us/bingmaps/articles/create-a-custom-map-url
