### ISSUE TITLE
HTML5 Geolocation ? 

### ISSUE THREAD

**Issue by didaskein** [Microsoft/BotBuilder-Location#113]
Can we have natively Geolocation with HTML5 inside Web Chat Channel ? https://www.w3schools.com/html/html5_geolocation.asp

Thank you in advance,

**Comment by amitbend** [comment]
This is a great suggestion

**Comment by rbrundritt** [comment]
Bot platforms don't generally provide access to user location information. It may be possible for a bot client to use the HTML5 geolocaiton API to request the user location, but not the bot itself. This is something the creators of the bot clients would need to build.
