### ISSUE TITLE
Support sending of location via DirectLine API

### ISSUE THREAD

**Issue by camer314** [microsoft/BotBuilder-Location#114]
I have a Xamarin app using the DirectLine API. I also have the geo coordinates of the device but i have no way of passing them to the control.

The control should support sending of location for any channel, not just Facebook. Alternatively it should recognize latitude/longitude pairs in reply to the address prompt and thus I could just send that in response.

**Comment by IoTGirl** [comment]
There are no plans to offer Bing Maps through direct line API
