### ISSUE TITLE
Is it possible to add favorite location for a user without a dialog?

### ISSUE THREAD

**Issue by amitbend** [Microsoft/BotBuilder-Location#118]
Hey,
I have a bot which is mostly focused on one fixed location.
I would like to add it as a favorite location or just as an option when the user is being asked for the location.

Is there a way to do it?
Or is it on the dev plan?

**Comment by minekucukal** [comment]
Hi, Did you solve the problem? How can I solve the this problem? @amitbend

**Comment by amitbend** [comment]
I ended up writing something of my own, seems like this repo is pretty much dead
