### ISSUE TITLE
clickable image cards

### ISSUE THREAD

**Issue by vmunnuru** [microsoft/BotBuilder-Location#130]
I want to make map images clickable,
<img width="678" alt="screen shot 2018-12-19 at 4 59 07 pm" src="https://user-images.githubusercontent.com/25169611/50217806-d76e4900-03af-11e9-839c-5fe9df2a0b2c.png">
currently our bot implemented as above, but we have to remove 1, 2... numbers from images and card images clickable (no more options for user input).

**Comment by IoTGirl** [comment]
You would need to leave the chat to get an interactive Map. I would add a URL link with the custom location as documented here: https://docs.microsoft.com/en-us/bingmaps/articles/create-a-custom-map-url
