### ISSUE TITLE
Current location node js

### ISSUE THREAD

**Issue by Emilianosanchezlopez** [microsoft/BotBuilder-Location#132]
**Bot framework V3, Node Js, Telegram channel, current location.**
Hello everyone, I am working with the Telegram channel and I would like to know which is the simplest method to obtain the current location (latitude and longitude) of a user using node js.

I see that there is a button for the Facebook Messenger channel, but it does not apply to other channels.

I would appreciate this information.
Greetings.

**Comment by esanchezlMBT** [comment]
@rbrundritt is there any news from this issue?.

**Comment by rbrundritt** [comment]
Not sure why you are asking me. I've made one pull request on this project. Perhaps @kgrashad knows.

**Comment by IoTGirl** [comment]
I am afraid we would just do the same search you would, https://www.bing.com/search?q=Node.js+User+location. Probably better to ask this question on a Node.Js forum.
