### ISSUE TITLE
Will this Location service can also be used from Microsoft Teams Application?

### ISSUE THREAD

**Issue by Santhosh0505** [microsoft/BotBuilder-Location#133]
I am trying to implement this Sharing Location service extention with a teams user. Can you please let me know that, will this work in Microsoft Teams Application or not?

**Comment by vunhutien** [comment]
i'm also looking for this

**Comment by Santhosh0505** [comment]
There is no direct way to access this kind of service in teams as far as I have concluded with, but I have used Task Module in teams where we can render a web page, where it will open a popup, there I have configured a dynamic conversation based Location service api where we can view the user with this kind of map response.
@vunhutien

**Comment by rbrundritt** [comment]
Haven't used this in a while but it was possible to us it in teams the last time I tried.

**Comment by vunhutien** [comment]
@Santhosh0505 @rbrundritt can you share your implementation, anyway that can ask for user to share their location (by native dialog or open web browser all is ok)? I'm stuck on this thing whole day and seem to be given up.

**Comment by Santhosh0505** [comment]
@vunhutien 
The primary goal of my implementation is to share a location search result to user with Maps interface which I have achived using Task Module with Bot Framework. But as I can understand that your requirement is to share the user's location using microsoft teams, this could only be possible if the Microsoft Teams app can fetch user's current location and send it, you can try with Places extention with Microsoft Teams application which allows user to share location.

**Comment by Santhosh0505** [comment]
> Haven't used this in a while but it was possible to us it in teams the last time I tried.

Yes, it was working fine with Task Module Interface for sharing Maps UI  with location pinned on it.
