### ISSUE TITLE
LocationResourceManager constructor should be public

### ISSUE THREAD

**Issue by ejadib** [Microsoft/BotBuilder-Location#39]
[Current constructor](https://github.com/Microsoft/BotBuilder-Location/blob/c4bdfa32c7190e92fc38ec02c6887edcace2dcf5/CSharp/BotBuilderLocation/LocationResourceManager.cs#L147) in the LocalzationResourceManager (C#) is internal and so it's not possible to inherit from it to override the prompt strings

**Comment by ejadib** [comment]
@kgrashad we just submitted #40 to fix this.

**Comment by ejadib** [comment]
@kgrashad Any idea when this could be pushed to NuGet? We are doing some updates on the [ContosoFlowers sample](https://github.com/southworkscom/BotBuilder-Samples/tree/csharp-contosoflowers-locationlocalization) and we need this change :)

**Comment by kgrashad** [comment]
@ejadib I sent package 1.1.0 to @Andrea-Orimoto to be signed and released.

**Comment by kgrashad** [comment]
https://www.nuget.org/packages/Microsoft.Bot.Builder.Location/1.1.0
