### ISSUE TITLE
Localization issue with BotBuilder 3.5.1 

### ISSUE THREAD

**Issue by pcostantini** [Microsoft/BotBuilder-Location#44]
Hi!
Since version 3.4.4 a few changes have been commited to the botbuilder repo that I think have broken how this control reads its localized strings.

![image](https://cloud.githubusercontent.com/assets/57197/21785848/01b522ea-d6a0-11e6-8888-be90b5655962.png)

[These changes, introduced in Session.vgettext](https://github.com/Microsoft/BotBuilder/commit/95964899c3499921ef01559c87d08e115fd9a2e9#diff-4d195306b099c075a106a81d0bccb2b3), are now passing the module's name along with the resource key.

V3.4.4
![localization-3 4](https://cloud.githubusercontent.com/assets/57197/21784295/acd39ca8-d699-11e6-9e2f-0198f7d0fe03.png)

V3.5.1
![localization-1](https://cloud.githubusercontent.com/assets/57197/21784305/b680fe44-d699-11e6-9dbf-ddca0bb14218.png)

The final resource string (later resolved by DefaultLocalizer) is prepending the namespace 'botbuilder-location' to the key 'botbuilder-location:TitleSuffix':
![localization-2](https://cloud.githubusercontent.com/assets/57197/21784371/ee4213ae-d699-11e6-90a3-96352ed04d47.png)

A fix could be to avoid prefixing the localization key with the exports.LibraryName in the [constants](https://github.com/Microsoft/BotBuilder-Location/blob/master/Node/core/src/consts.ts).
I'm not sure if this impacts other areas, so far I haven't done any further testing.
E.g.:

````JavaScript
export const Strings = {
    "AddressSeparator": "AddressSeparator",
    "AskForEmptyAddressTemplate": "AskForEmptyAddressTemplate",
    ...
````

**Comment by kgrashad** [comment]
@pcostantini, thanks for the detailed report bug. I am able to repro this as well. Your suggestion does fix the issue. I will be doing some further testing today and will push a pull request if all is working as expected.

**Comment by kgrashad** [comment]
Hi @Stevenic, With regards to this bug, we noticed that the localization change broke us. Shouldn't this have been a major version bump up since its breaks backwards compatibility as per https://docs.npmjs.com/getting-started/semantic-versioning

**Comment by kgrashad** [comment]
#51

**Comment by kgrashad** [comment]
The fix is now published to [npm](https://www.npmjs.com/package/botbuilder-location)
