### ISSUE TITLE
mapArea & pushpin invalid format

### ISSUE THREAD

**Issue by msimecek** [Microsoft/BotBuilder-Location#54]
On a server with locale set to use decimal numbers with comma (i.e. 50,03861) the control doesn't show any map. It sends parameters like this: `mapArea=50,03861,14,44113,50,05002,14,45956` and gets this error:

{"authenticationResultCode":"ValidCredentials","brandLogoUri":"http:\/\/dev.virtualearth.net\/Branding\/logo_powered_by.png","copyright":"Copyright © 2017 Microsoft and its suppliers. All rights reserved. This API cannot be accessed and the content and any results may not be used, reproduced or transmitted in any manner without express written permission from Microsoft Corporation.","errorDetails":["One or more parameters are not valid.","**mapArea: This parameter value has an invalid format.**","**pushpin: This parameter value has an invalid format.**"],"resourceSets":[],"statusCode":400,"statusDescription":"Bad Request","traceId":"9b6284056aea46c99cf5c301e32fae0e|DB40170149|7.7.0.0|"}

Map shows allright in a web browser after correcting manually to `mapArea=50.03861,14.44113,50.05002,14.45956`.
I guess it's because of incorrect handling of double values in BingGeoSpatialService.

**Comment by kgrashad** [comment]
Good catch. We need to pass Culture Invariant when we use String.Format.

**Comment by kgrashad** [comment]
pull-request #61
