### ISSUE TITLE
Unnecessary confirmation of location

### ISSUE THREAD

**Issue by craigomatic** [Microsoft/BotBuilder-Location#56]
Inside the LocationDialog method ResumeAfterChildDialogInternalAsync it seems to be asking for confirmation again (after I've already confirmed the address is correct). 

This seems a little unnecessary, perhaps that code could be removed?

It's also very strange to have the location dialog hardcoded to confirm that a package will be shipped to that location with no simple way to override it.

This is similar to one of the issues mentioned in #55

**Comment by kgrashad** [comment]
Hi @craigomatic , we can provide an option to allow you to skip this last confirmation. I am adding this to our Feb release.

**Comment by garypretty** [comment]
Would also be good to be able to override this confirmation message if we don't want to skip it.

**Comment by kgrashad** [comment]
@garypretty You can already do this through providing a LocationResourceManager to LocationDialog.

**Comment by haligasd** [comment]
thank you.  was going to ask for this today.  biggest deal is when we use this with facebook and we just want their lat / lng (which is all we get anyway) but we don't want another confirm question in the flow

**Comment by garypretty** [comment]
Hi. Is this release imminent?

**Comment by haligasd** [comment]
+1.  We really need this as well

**Comment by craigomatic** [comment]
I've coded this for C# on the V2 branch if it's helpful: https://github.com/craigomatic/BotBuilder-Location/tree/V2

Will do NodeJS later today also.

**Comment by haligasd** [comment]
great i am using c# when will it make it into nuget?

**Comment by kgrashad** [comment]
Thanks @craigomatic . V2 Is still has sometime to be released. If you would like you can create this as a hotfix to master branch. Please call your branch (hotfix/skip-final-confirmation-option). I will review it and merge it. Thanks!

**Comment by haligasd** [comment]
cool i see the pull request. how does this work from here?  will this be a 1.2 release?

**Comment by eswarkp** [comment]
May i know in which release this change will be available to install through npm?

**Comment by kgrashad** [comment]
@eswarkp I am planning to release this to npm tomorrow (Thursday March 2nd)

**Comment by haligasd** [comment]
and nuget?

**Comment by kgrashad** [comment]
npm released version 1.1.0
nuget should be release within a day or two max.

**Comment by HemalR** [comment]
+1 to this - building a bot that needs location but not for package shipping. The thread seems to suggest that this has now been made optional - is there a link to the documentation on how to make this optional that someone can point me to?

Thanks in advance!

**Comment by haligasd** [comment]
https://github.com/craigomatic/BotBuilder-Location/commit/be1b3e9baf69ed78acd9ce8f3a70a669998663c5

just a flag you pass in the constructor

LocationOptions.SkipFinalConfirmation

**Comment by haligasd** [comment]
@kgrashad any updates on csharp release?

**Comment by kgrashad** [comment]
@haligasd released on https://www.nuget.org/packages/Microsoft.Bot.Builder.Location/1.2.0 Can you please give it a try and confirm that everything is working smoothly for you?

**Comment by haligasd** [comment]
@kgrashad works awesome!!  thank you
