### ISSUE TITLE
Problem with prompts in the chat

### ISSUE THREAD

**Issue by SomaSharathSurya** [Microsoft/BotBuilder-Location#62]
![capture](https://cloud.githubusercontent.com/assets/25243569/22202236/40382b46-e18d-11e6-8d8b-854443841f10.PNG)

I am getting "botbuilder-location:SingleResultFound" prompts in the chat instead of actual message. Please help me to fix this issue asap.

Thanx in advance

**Comment by kgrashad** [comment]
Hi @SomaSharathSurya,

This was caused by a breaking change in botbuilder sdk. We already checked in a fix but waiting to get it in npm.

One way to unblock yourself is to force botbuilder to a version before the breaking change. In package.json change botbuilder version to:
"botbuilder": "3.4.4",

**Comment by SomaSharathSurya** [comment]
Hi @kgrashad 

Ive tried changing botbuilder version to 3.4.4 the bot is still showing the same prompt. Please help.

**Comment by kgrashad** [comment]
Hmmm. Can you try cloning this repo and requiring it from local file system until v1.0.3 makes it to npm?

**Comment by kgrashad** [comment]
http://browsenpm.org/help#cloningamodulefromGithub

**Comment by SomaSharathSurya** [comment]
Hey @kgrashad  Ive tried cloning this repo(and changed the botbuilder version)  and executed it still i have the same problem.  please tell me what to do?

**Comment by kgrashad** [comment]
The fix is now published to [npm](https://www.npmjs.com/package/botbuilder-location)
