### ISSUE TITLE
No location results are passed by waterfall after sending facebook location quick reply

### ISSUE THREAD

**Issue by amitbend** [Microsoft/BotBuilder-Location#66]
After sending this on the first:
`                var options = {
                    prompt: prompts.locationPrompt,
                    useNativeControl: true
                };
                locationDialog.getLocation(session, options);`
i'm checking for results in the next waterfall function and getting nothing back: (means not getting into this "if" statement.
`
            if (args.response){
                session.send(JSON.stringify(args));
            }
`

I'm just trying to fetch the lat/lng from facebook.
any idea why it happens?

**Comment by kgrashad** [comment]
Can you try first running the sample app and see if it is working for you:
https://github.com/Microsoft/BotBuilder-Location/blob/master/Node/sample/app.js

**Comment by amitbend** [comment]
@kgrashad yes, it works only when `requiredFields` is specified (and i don't want to ask the user for all this details - just get the lat/lng)

**Comment by kgrashad** [comment]
I can repro this issue. @mbadreldin can you have a look and get it in a hotfix.

**Comment by mbadreldin** [comment]
Hey @amitbend,
Thanks for reporting this. I made a hotfix and will update the NPM package shortly.

**Comment by amitbend** [comment]
Great news, thanks

**Comment by kgrashad** [comment]
npm package updated. @amitbend please confirm that the update fixed your scenario.

**Comment by kgrashad** [comment]
#69

**Comment by amitbend** [comment]
@kgrashad I can confirm that issue is solved now. thanks @kgrashad
