### ISSUE TITLE
Node.js : Localize dialog commands

### ISSUE THREAD

**Issue by remydavid** [Microsoft/BotBuilder-Location#88]
Current node confirm dialog implementation is :

    function parseBoolean(input) {
    input = input.trim();
    var yesExp = /^(y|yes|yep|sure|ok|true)/i;
    var noExp = /^(n|no|nope|not|false)/i;
    if (yesExp.test(input)) {
        return true;
    }
    else if (noExp.test(input)) {
        return false;
    }
    return undefined;
}

Which does not allow for localization.
Regex should test for locale/{current_locale}/BotBuilder.json confirm_yes and confirm_no values.

The same for other default command : other, help, reset, etc

Similar to #67 for C#

**Comment by kgrashad** [comment]
Dupe #67
