### ISSUE TITLE
Question : Using BingMapsRestToolkit & evolutions of the location control

### ISSUE THREAD

**Issue by TechWatching** [microsoft/BotBuilder-Location#91]
I was wondering why the BingGeoSpatialService  is not using the BingMapRestToolkit package. Is this a deliberate choice or is this something planned for the future ? 

By the way what are the evolutions planned for the bing location control ? Is displaying a route on the control on the roadmap ?

**Comment by IoTGirl** [comment]
There are no planned updates to the Rest Toolkit
