### ISSUE TITLE
Showing Multiple Location in same Map

### ISSUE THREAD

**Issue by ghost** [Microsoft/BotBuilder-Location#95]
Currently if we get EstimatedTotal >1 then we are showing these location in two different cards.
What should be done if I want to show two different location in the same card?

The following code I am using to display different Cards if EstimatedTotal >1

 

> var heroCard = new HeroCard();
>             var attachments = new List<Attachment>();
>             long Len = locationsResponse.ResourceSets[0].EstimatedTotal;
>             long i;
>             string sOut;
>             var locationsCardReply= context.MakeMessage();
>             for (i = 0; i < Len; i++)
>             {
>                 sOut = string.Format(ImageUrlByPoint,
>                                         locationsResponse.ResourceSets[0].Resources[i].Point.Coordinates[0],
>                                         locationsResponse.ResourceSets[0].Resources[i].Point.Coordinates[1],
>                                         1) + "&key=" + apiKey;
>                 var image = new CardImage(url: sOut);
>                 heroCard.Images = new[] { image };
>                 attachments.Add(heroCard.ToAttachment());
>             }
>             locationsCardReply.Attachments = attachments;
>             locationsCardReply.AttachmentLayout = AttachmentLayoutTypes.Carousel;

Please reply if anyone got the solution.

**Comment by rbrundritt** [comment]
It is possible to render multiple pins on a map, but the issue you will find is that unless the locations are close together, you will end up with a map that is too zoomed out if a single location is far away from the others. If this happens, those that are close together would overlap and be difficult to see.
