### ISSUE TITLE
Decimal separator

### ISSUE THREAD

**Issue by NandoMuttley** [Microsoft/BotBuilder-Location#96]
If I set Bot Emulator to locale with comma as decimal separator (e.g. it) I get a broken map image due a incorrect coordinates

"attachments": [
    {
      "contentType": "application/vnd.microsoft.card.hero",
      "content": {
        "subtitle": "95 Water St, New York, NY",
        "images": [
          {
            "url": "https://dev.virtualearth.net/REST/V1/Imagery/Map/Road?form=BTCTRL&mapArea=40,6988751528792,-74,0195035709466,40,7066005880206,-74,0059170523339&mapSize=500,280&pp=40,7027378704499,-74,0127103116403;1;1&dpi=1&logo=always&key=Akwtog-Wb5YkszvsxY_nYKbus80tukI1ZL82tQeHvnwWJ2PVGmqchWkeJuDcOpqN"
          }
        ]
      }
    }
  ],

40,6988751528792 instead of 40.6988751528792 and so on.

Suggested fix --> BingGeoSpatialService.GetLocationMapImageUrl (force culture to "en-US")

CultureInfo cultureEn = new CultureInfo("en-US");

            if (location.BoundaryBox != null && location.BoundaryBox.Count >= 4)
            {
                return string.Format(cultureEn,
                    ImageUrlByBBox,
                    location.BoundaryBox[0],
                    location.BoundaryBox[1],
                    location.BoundaryBox[2],
                    location.BoundaryBox[3],
                    point.Coordinates[0],
                    point.Coordinates[1], index)
                    + "&key=" + apiKey;
            }
            else
            {
                return string.Format(cultureEn, ImageUrlByPoint, point.Coordinates[0], point.Coordinates[1], index) + "&key=" + apiKey;
            }

**Comment by rbrundritt** [comment]
The Bing Maps team has a .NET library for the REST services. Might be good to use that instead, but would be a decent amount of rework. Here is how it handles coordinates:

string.Format(CultureInfo.InvariantCulture, "{0:0.#####},{1:0.#####}", Latitude, Longitude);

Decimal places after the 5th one make no real difference. Using invariant culture will make sure that decimals are used for decimals and not commas.

**Comment by rbrundritt** [comment]
This is fixed
